##
## Makefile for PSU_2016_malloc in /Users/hubert_i/Documents/Shared/PSU_2016/PSU_2016_malloc
##
## Made by Leo HUBERT
## Login   <leo.hubert@epitech.eu>
##
## Started on  Mon Jan 23 21:45:33 2017 Leo HUBERT
## Last update Mon Jan 23 21:45:33 2017 Leo HUBERT
##

all:
		@make --no-print-directory -C sources/

clean:
		@make clean --no-print-directory -C sources/

fclean:
		@make fclean  --no-print-directory -C sources/

re:		fclean all

.PHONY: 	all encore clean fclean re
